[downloads]
# Folder where original files will be downloaded then moved to a sub 'YYYY-MM-DD/format' folder
root_folder = "./downloads"
# Name of the folder where final FLAC files will be exported
flac_folder = "flac"
# Name of the folder where final MP3 files will be exported
mp3_folder = "mp3"
# Name of the folder where final WAV files will be exported
wav_folder = "wav"
# Download backend ('deezer', 'qobuz')
backend = "deezer"
# Download format (false = MP3@320, true = FLAC@44.1)
lossless = false
# Playlist to download (must be public if Spotify)
playlist_url = ""

[metadata]
# Relevant remix tokens (everything else will be removed from the title)
supported_remix_tokens = ["remix", "bootleg", "flip", "edit", "vip"]
# Delimiter used to separate contributing artists tag
artist_delimiter = "; "
# Indicates whether or not to remove featuring artists from a track title and file name
remove_feat_from_title = true
# Indicates whether or not to use the title of a single as its album or leave the tag blank
tag_single_album = false
# Default genre to use when tagging tracks
default_genre = ""

[soundcloud]
# Website names that will be detected as a download gate
supported_download_gates = ["hypeddit", "toneden"]
# Use an interactive browser instance to download from gates (experimental)
use_web_driver = false

# Credentials live in 'secrets.toml' (see secrets.toml.example)
